### ISSUE TITLE
Add a `LICENSE` file

### ISSUE THREAD

**Issue by wasertech** [thorstenMueller/Audio-to-Voice-Dataset#2]
Please license your code otherwise I can't touch it. Anything is fine, I guess, just license it please.

**Comment by wasertech** [comment]
> Licensing your code is a critical step in the development and distribution process, as it defines how others can use, modify, and share your work. Without a license, your code is considered proprietary by default, meaning no one else can legally copy, distribute, or modify it without your explicit permission. This can severely limit collaboration and contribution, which are often vital for open-source projects. By choosing an appropriate license, you make it clear under what terms your work can be used, which can encourage others to contribute, use, or even improve upon it. Licenses can range from permissive, like the MIT License, which allows great freedom to users, to more restrictive ones like the GNU GPL, which requires derivative works to also be open source. It's important to select a license that aligns with your goals for the project.

For this project, something simple like the MIT sounds perfectly reasonable, but please choose any that fancy you.

You can easily [add a license to a project by using the GitHub interface](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

**Comment by thorstenMueller** [comment]
Thanks for pointing out 👍. I'll check and add a license file soon.

**Comment by thorstenMueller** [comment]
I've just added the MIT license to the repo. Looking forward to your ideas on code improvement 😊.
Thanks again for pointing the licensing out.
